# Generated by Django 3.2.2 on 2021-05-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cliente_colaborador_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.colaborador'),
        ),
    ]
