# Generated by Django 3.1.7 on 2021-06-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210522_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Colaborador',
            new_name='repartidor',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Localizacion',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='Pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccionEntrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tariga',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tarifa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=3),
        ),
    ]
