# Generated by Django 3.1.7 on 2021-06-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210610_0445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Comerciante',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='comerciante',
        ),
    ]
