# Generated by Django 3.1.7 on 2021-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipodecomprobante',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
