# Generated by Django 3.1.7 on 2021-06-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pedido_tipodecomprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipodecomprobante',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
