# Generated by Django 3.1.7 on 2021-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pedido_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='RUC',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
