# Generated by Django 3.1.7 on 2021-06-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210622_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='RUC',
            new_name='RUC_Factura',
        ),
    ]
