# Generated by Django 3.1.7 on 2021-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210622_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='RUC_Factura',
            field=models.CharField(default='-', max_length=11, null=True),
        ),
    ]
